networks:
  default: {}
  sandbox: {}
  traefik:
    external: true
    name: traefik
secrets:
  MMH_EMAIL_PASSWORD:
    external: true
    name: MMH_EMAIL_PASSWORD
  MMH_MARIADB_PASSWORD:
    external: true
    name: MMH_MARIADB_PASSWORD
  MMH_MARIADB_ROOT_PASSWORD:
    external: true
    name: MMH_MARIADB_ROOT_PASSWORD
services:
  birt:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/production/birt/Dockerfile
    depends_on:
    - mariadb
    deploy:
      labels:
        traefik.enable: "false"
      placement:
        constraints:
        - node.labels.gluster == true
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 2.5G
        reservations:
          cpus: '0.25'
          memory: 1G
    environment:
      BIRT_DOCKER: '1'
      DB_HOST: mariadb
      DB_NAME: mmh
      DB_USER: mmh
      JAVA_OPTS: -Xmx2g -Xms2g
      JVM_OPTS: -Xmx2g -Xms2g -XX:MaxPermSize=512m
    image: registry.nixc.us/mmh-birt:production
    labels:
      traefik.expose: "false"
    networks:
      default: {}
    restart: always
    secrets:
    - source: MMH_MARIADB_PASSWORD
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - /etc/localtime:/etc/localtime:ro
  cron:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/production/cron/Dockerfile
    deploy:
      replicas: 1
    image: registry.nixc.us/mariadb-cron:production
    networks:
      default: {}
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  mariadb:
    deploy:
      labels:
        traefik.enable: "false"
      placement:
        constraints:
        - node.labels.db == true
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MMH_MARIADB_ROOT_PASSWORD
      TZ: America/New_York
    image: registry.nixc.us/mariadb-base:production
    networks:
      default: {}
      sandbox: {}
    secrets:
    - source: MMH_MARIADB_ROOT_PASSWORD
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /mnt/tank/persist/mmh/production/db/mariadb:/var/lib/mysql:rw
  nginx:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/production/nginx/Dockerfile
    depends_on:
    - php
    deploy:
      labels:
        traefik.backend: mmh-nginx-c5
        traefik.backend.loadbalancer.stickiness: "false"
        traefik.backend.loadbalancer.swarm: "true"
        traefik.docker.network: traefik
        traefik.enable: "true"
        
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.redirect.regex: ^https?://michiganmodelforhealth.org/(.*)
        traefik.frontend.redirect.replacement: https://www.michiganmodelforhealth.org/$${1}
        traefik.frontend.rule: Host:www.michiganmodelforhealth.com,www.michiganmodelforhealth.net,www.michiganmodelforhealth.org,michiganmodelforhealth.com,michiganmodelforhealth.net,michiganmodelforhealth.org,www.mmforhealth.net,www.mmforhealth.com,www.mmforhealth.org,mmforhealth.net,mmforhealth.com,mmforhealth.org
        traefik.port: '80'
        traefik.redirectorservice.frontend.entryPoints: http
        traefik.redirectorservice.frontend.redirect.entryPoint: https
        traefik.tags: traefik
        traefik.webservice.frontend.entryPoints: https
      placement:
        constraints:
        - node.labels.gluster == true
        preferences:
        - spread: node.id
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
      restart_policy:
        condition: on-failure
      update_config:
        delay: 5s
        parallelism: 1
    environment:
      IS_PROD: 0
    image: registry.nixc.us/mmh-nginx:production
    networks:
      default: {}
      traefik: {}
    user: 1000:1000
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /mnt/tank/persist/mmh/production/logs/nginx:/var/log/nginx:rw
    - /mnt/tank/persist/mmh/production/data/c5-app-files:/var/www/html/application/files:rw
  php:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/production/php/Dockerfile
    depends_on:
    - mariadb
    - redis
    deploy:
      labels:
        traefik.enable: "false"
      placement:
        constraints:
        - node.labels.gluster == true
        preferences:
        - spread: node.id
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 1
    environment:
      DB_HOST: mariadb
      DB_NAME: mmh
      DB_USER: mmh
      IS_PROD: 1
      SITE_URL: https://www.michiganmodelforhealth.org
      USE_SMTP: 1
    image: registry.nixc.us/mmh-php:production
    networks:
      default: {}
    secrets:
    - source: MMH_EMAIL_PASSWORD
    - source: MMH_MARIADB_PASSWORD
    user: 1000:1000
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /mnt/tank/persist/mmh/production/data/c5-files:/home/production/mmh-repo/secure_files:rw
    - /mnt/tank/persist/mmh/production/data/c5-app-files:/var/www/html/application/files:rw
  redis:
    deploy:
      labels:
        traefik.enable: "false"
      placement:
        constraints:
        - node.labels.db == true
        preferences:
        - spread: node.id
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    entrypoint: redis-server --appendonly yes
    image: redis
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 200k
    networks:
      default: {}
    restart: always
    volumes:
    - /mnt/tank/persist/mmh/production/db/redis:/data:rw
    - /etc/localtime:/etc/localtime:ro
  sshd:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/production/sshd/Dockerfile
    deploy:
      labels:
        traefik.enable: "false"
      placement:
        constraints:
        - node.hostname == dewitt.improvingmipractices.com
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0'
          memory: 100M
    image: registry.nixc.us/mmh-sshd:production
    labels:
      traefik.enable: "false"
    networks:
      sandbox: {}
    ports:
    - mode: host
      published: 2223
      target: 22
    - mode: host
      published: 2224
      target: 22
    restart: always
    volumes:
    - /etc/ssh/sshd_config:/etc/ssh/sshd_config:ro
version: '3.7'

